// apps/api/src/routes/agent.routes.js
import * as agentService from '../services/agent.service.js'
import * as taskService from '../services/task.service.js'
import * as scopeService from '../services/agent-scope.service.js'
import * as memoryService from '../services/memory.service.js'
import * as taskKnowledgeService from '../services/task-knowledge.js'
import { executeCustomSkill } from '../services/skill-executor.service.js'
import { errorResponse, AppError } from '../utils/errors.js'
import { requireAdmin, requirePermission } from '../middleware/rbac.js'
import { 
  uuidParam, 
  agentIdParam, 
  createAgentSchema, 
  updateAgentSchema, 
  dispatchTaskSchema,
  addSkillSchema 
} from '../schemas/validation.js'

// // ── Task Rate Limiting — Redis-backed, falls back to in-memory ─────────────────
// The original in-memory Map reset on server restart and was wrong in multi-
// instance deployments. Redis INCR+EXPIRE gives a shared, persistent counter
// across all instances without requiring a lock.

const TASK_RATE_WINDOW_MS = 60_000 // 1 minute
const TASK_RATE_WINDOW_S  = 60     // same, in seconds (for Redis EXPIRE)

// ── Rule-based prompt compressor (LLM-free fallback) ─────────────────────────
// Never modifies lines containing numbers or measurements — those are project-
// specific facts (quantities, dimensions, metrics) that must be preserved exactly.
// ── Local rule-based prompt compressor ─────────────────────────────────────
// Pure regex — no external package. Two-pass strategy:
//   Pass 1: Strip entire boilerplate sections auto-generated by the archetype
//           engine (## YOUR ROLE, ## HOW TO WORK). These add 0 domain value.
//   Pass 2: Line-level filler word substitutions (preserves lines with numbers).
//
// Savings on a typical agent prompt: 15-30% with zero meaning loss.
function ruleBasedCompress(prompt) {
  // ── Pass 1: Section stripping ───────────────────────────────────────────
  // Remove entire ## sections that are pure archetype boilerplate.
  // These are identified by their fixed opening lines (generated by buildSystemPrompt).
  const STRIP_SECTIONS = [
    // Generic HOW TO WORK boilerplate
    /## HOW TO WORK[\s\S]*?(?=\n## |$)/gi,
    // Generic YOUR ROLE boilerplate (only when it starts with the generic phrase)
    /## YOUR ROLE\n(?:You handle a wide range[\s\S]*?)(?=\n## |$)/gi,
    // Generic AGENT ROLE & CAPABILITIES section (auto-generated from archetype name)
    // Keep only the first descriptive line, drop the rest
    /## AGENT ROLE & CAPABILITIES\n(.*?)\n[\s\S]*?(?=\n## |$)/gi,
  ]
  let out = prompt
  for (const rx of STRIP_SECTIONS) {
    out = out.replace(rx, (match, keep) => {
      // For AGENT ROLE: keep just the first line (the specialised description)
      if (/AGENT ROLE/i.test(match) && keep) return `## AGENT ROLE\n${keep.trim()}`
      return ''
    })
  }

  // ── Pass 2: Line-level filler substitutions ─────────────────────────────
  out = out.split('\n').map(line => {
    if (/\d/.test(line)) return line // never touch lines with numbers
    return line
      // Verbose openers → drop
      .replace(/^(Please |You should |Make sure to |Always remember to |It is important to |Note that |Be sure to |Remember to |Feel free to |Try to |You must |You need to )/i, '')
      // Verbose connectives → shorter
      .replace(/\bIn order to\b/gi, 'To')
      .replace(/\bDue to the fact that\b/gi, 'Because')
      .replace(/\bAt this point in time\b/gi, 'Now')
      .replace(/\bIn the event that\b/gi, 'If')
      .replace(/\bPrior to\b/gi, 'Before')
      .replace(/\bSubsequent to\b/gi, 'After')
      .replace(/\bWith the exception of\b/gi, 'Except')
      .replace(/\bFor the purpose of\b/gi, 'For')
      .replace(/\bIn the case that\b/gi, 'If')
      .replace(/\bIn the case where\b/gi, 'When')
      .replace(/\bIn terms of\b/gi, 'For')
      .replace(/\bWith respect to\b/gi, 'For')
      .replace(/\bWith regard to\b/gi, 'For')
      .replace(/\bAs a result of\b/gi, 'Due to')
      .replace(/\bOn the other hand\b/gi, 'However')
      .replace(/\bIt is worth noting that\b/gi, 'Note:')
      .replace(/\bIt should be noted that\b/gi, 'Note:')
      .replace(/\bIn addition to this\b/gi, 'Also')
      .replace(/\bIn addition to the above\b/gi, 'Also')
      .replace(/\bFor example,?\b/gi, 'E.g.')
      .replace(/\bFor instance,?\b/gi, 'E.g.')
      .replace(/\bSuch as\b/gi, 'like')
      .replace(/\bAs well as\b/gi, 'and')
      .replace(/\bIn order for\b/gi, 'So')
      .replace(/\bMake sure that you\b/gi, 'Ensure')
      .replace(/\bMake sure to\b/gi, 'Ensure')
      .replace(/\bEnsure that you\b/gi, 'Ensure')
      .replace(/\bBe sure that\b/gi, 'Ensure')
      .replace(/\bYou are required to\b/gi, 'Must')
      .replace(/\bYou are expected to\b/gi, 'Must')
      .replace(/\bYou are responsible for\b/gi, 'Handle')
      .replace(/\bYou are able to\b/gi, 'Can')
      .replace(/\bYou will be able to\b/gi, 'Can')
      .replace(/\bIt is possible to\b/gi, 'Can')
      .replace(/\bIt is necessary to\b/gi, 'Must')
      .replace(/\bIt is essential that\b/gi, 'Must')
      .replace(/\bAll of the\b/gi, 'All')
      .replace(/\bEach of the\b/gi, 'Each')
      .replace(/\bAny of the\b/gi, 'Any')
      .replace(/\bNone of the\b/gi, 'None')
      .replace(/\bBoth of the\b/gi, 'Both')
      .replace(/\bIf and when\b/gi, 'When')
      .replace(/\bIf and only if\b/gi, 'Only if')
      .replace(/\bAs much as possible\b/gi, 'when possible')
      .replace(/\bAs soon as possible\b/gi, 'ASAP')
      // Trailing whitespace
      .replace(/[ \t]+$/, '')
  }).join('\n')

  return out.replace(/\n{3,}/g, '\n\n').trim()
}

// Fallback in-memory counter (used when Redis is unavailable)
const tenantTaskCounts = new Map()
const TASK_RATE_CACHE_MAX = 10_000

async function resolveTaskRateLimit(tenantId) {
  const { getTaskRateLimit } = await import('../services/plan-limits.service.js')
  return getTaskRateLimit(tenantId)
}

async function checkTenantTaskRateLimit(tenantId) {
  const limit = await resolveTaskRateLimit(tenantId)

  // ── Redis path (preferred) ──────────────────────────────────────────────
  try {
    const { getRedisConnection } = await import('../services/queue.service.js')
    const redis = getRedisConnection()
    const key = `rate:tasks:${tenantId}`
    const count = await redis.incr(key)
    if (count === 1) {
      // First call in this window — set TTL so the key auto-expires
      await redis.expire(key, TASK_RATE_WINDOW_S)
    }
    if (count > limit) {
      // Get remaining TTL so we can tell the user when to retry
      const ttl = await redis.ttl(key)
      throw new AppError(
        'TENANT_RATE_LIMITED',
        `Task dispatch limit of ${limit} per minute reached. Retry in ${ttl > 0 ? ttl : 60}s.`,
        429
      )
    }
    return // Redis check passed
  } catch (err) {
    if (err.code === 'TENANT_RATE_LIMITED') throw err // re-throw rate limit errors
    // Redis unavailable — fall through to in-memory fallback
  }

  // ── In-memory fallback ──────────────────────────────────────────────────
  const now = Date.now()
  const entry = tenantTaskCounts.get(tenantId)

  if (!entry || now - entry.windowStart >= TASK_RATE_WINDOW_MS) {
    if (!entry && tenantTaskCounts.size >= TASK_RATE_CACHE_MAX) {
      const oldest = tenantTaskCounts.keys().next().value
      if (oldest !== undefined) tenantTaskCounts.delete(oldest)
    }
    tenantTaskCounts.set(tenantId, { count: 1, windowStart: now, limit })
    return
  }

  if (entry.count >= entry.limit) {
    const resetIn = Math.ceil((TASK_RATE_WINDOW_MS - (now - entry.windowStart)) / 1000)
    throw new AppError(
      'TENANT_RATE_LIMITED',
      `Task dispatch limit of ${entry.limit} per minute reached. Retry in ${resetIn}s.`,
      429
    )
  }

  entry.count++
}

export default async function agentRoutes(fastify) {
  const auth = { preHandler: [fastify.authenticate] }
  const adminAuth = { preHandler: [fastify.authenticate, requireAdmin] }

  // POST /tenants/:tenantId/agents
  fastify.post('/tenants/:tenantId/agents', {
    schema: { params: uuidParam, ...createAgentSchema },
    preHandler: [fastify.authenticate, requirePermission('agent:create')]
  }, async (req, reply) => {
    try {
      const agent = await agentService.createAgent({ tenantId: req.params.tenantId, data: req.body, userId: req.user.sub })
      return reply.status(201).send({ success: true, data: agent, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/generate — AI-powered agent creation
  // Body: { prompt: string }
  // Returns: { name, description, archetype, systemPrompt, autonomyLevel, suggestedTools }
  fastify.post('/tenants/:tenantId/agents/generate', {
    preHandler: [fastify.authenticate, requirePermission('agent:create')]
  }, async (req, reply) => {
    try {
      const { tenantId } = req.params
      const { prompt } = req.body || {}

      if (!prompt || typeof prompt !== 'string' || prompt.trim().length < 10) {
        return reply.status(400).send({ error: { code: 'INVALID_PROMPT', message: 'Prompt must be at least 10 characters.' } })
      }

      const systemPrompt = `You are an agent designer for the Kuvalam AI agent platform. Given a user's description of what they want an agent to do, generate a JSON object with:
- "name": A short, memorable name for this agent (max 40 chars)
- "description": A one-line summary of the agent's purpose and capabilities
- "archetype": The best-fit role archetype for this agent. Choose from: data-analyst, research, customer-support, developer, browser-automation, coordinator, planner, compliance, document, agent-generation, engineering, scientific, medical, news-media, insurance, banking, iot, generalist — or use a custom descriptive archetype if none fits.
- "systemPrompt": Concise but thorough instructions for the agent (80-200 words). Include:
  * The agent's role and primary objective
  * Step-by-step operating procedure
  * Key rules and constraints
  * Tool usage guidance
  * Output format expectations
- "autonomyLevel": One of: SUPERVISED, GUARDED, AUTONOMOUS
  * SUPERVISED: agent asks for approval before taking any external action
  * GUARDED: agent can take low-risk actions autonomously, asks for high-risk
  * AUTONOMOUS: agent operates freely (for internal/cron tasks)
- "suggestedTools": Array of relevant tool names this agent should use.

Key system tools: list_tables, describe_table, query, read_file, write_file, browse_url, web_search, calculator, clock, publish_dashboard_report
Key connector tools: jira__search_issues, jira__create_issue, slack__post_message, gmail__send_email, github__create_issue, db__query, confluence__search, salesforce__query, stripe__list_charges

Rules:
- Match the archetype to the described role.
- For DB/data agents include list_tables, describe_table, query.
- For browser/web agents include browse_url, web_search.
- System prompt should be practical, action-oriented, include concrete tool-calling patterns.
- Return ONLY valid JSON — no markdown, no backticks, no explanation.`

      const messages = [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Create an agent that: ${prompt.trim()}` },
      ]

      // Get tenant LLM config
      const { query: dbQuery } = await import('../db/pool.js')
      const { rows } = await dbQuery(
        'SELECT llm_config FROM tenants WHERE id = $1',
        [tenantId]
      )
      const llmConfig = rows?.[0]?.llm_config || {}

      const { complete } = await import('../services/llm.service.js')

      const result = await complete({
        tenantId,
        agentId: 'agent-generator',
        messages,
        llmConfig,
        useSystemLlm: true,
        temperature: 0.2,
        maxTokens: 8192,
        goal: `Generate agent from prompt: ${prompt.trim().slice(0, 80)}`,
      })

      // Parse the LLM response as JSON
      const text = (result.content || '').trim()
      let parsed
      try {
        const clean = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '')
        parsed = JSON.parse(clean)
      } catch (e) {
        // Log the raw output to a file for debugging
        const fs = await import('fs')
        fs.writeFileSync('/tmp/gen_debug.txt', text, 'utf-8')
        return reply.status(422).send({
          error: { code: 'PARSE_ERROR', message: `Failed to parse generated agent. Parse error: ${e.message}. Text length: ${text.length}. Last 200 chars: ${JSON.stringify(text.slice(-200))}`, raw: text.slice(0, 2000) }
        })
      }

      const resolvedName        = parsed.name || 'AI Generated Agent'
      const resolvedDescription = parsed.description || `AI-generated agent: ${prompt.trim().slice(0, 60)}…`
      const resolvedArchetype   = parsed.archetype || 'coordinator'

      // ── Enrich system prompt with our shared archetype template ──────────
      // The LLM often produces a generic "You are X" prompt. Use our structured
      // archetype template unless the LLM produced something substantially better
      // (>300 chars with clear HOW-TO-WORK instructions).
      const { generateAgentSystemPrompt } = await import('../services/agent.service.js')
      const llmPrompt = (parsed.systemPrompt || '').trim()
      const resolvedSystemPrompt = llmPrompt.length >= 300
        ? llmPrompt  // LLM produced a detailed prompt — keep it
        : await generateAgentSystemPrompt(resolvedName, resolvedDescription, resolvedArchetype, req.params.tenantId)

      return {
        data: {
          name: resolvedName,
          description: resolvedDescription,
          archetype: resolvedArchetype,
          systemPrompt: resolvedSystemPrompt,
          autonomyLevel: parsed.autonomyLevel || 'SUPERVISED',
          suggestedTools: parsed.suggestedTools || [],
        }
      }
    } catch (err) {
      if (err.message === 'LLM_RATE_LIMITED') {
        return reply.status(429).send({ error: { code: 'RATE_LIMITED', message: 'LLM rate limit reached. Please try again in a moment.' } })
      }
      if (err.message === 'LLM_AUTH_ERROR') {
        return reply.status(400).send({ error: { code: 'LLM_NOT_CONFIGURED', message: 'No LLM configured for this tenant. Set up an API key in Settings.' } })
      }
      return errorResponse(reply, err)
    }
  })

  // POST /tenants/:tenantId/agents/generate-skill — AI-powered skill creation
  // Body: { prompt: string, skillType: 'nl'|'api'|'code', language?: 'javascript'|'python' }
  // Returns: { name, description, type, instruction?, code?, url?, method?, headers?, bodyTemplate?, language? }
  fastify.post('/tenants/:tenantId/agents/generate-skill', {
    preHandler: [fastify.authenticate, requirePermission('agent:create')]
  }, async (req, reply) => {
    try {
      const { tenantId } = req.params
      const { prompt, skillType, language } = req.body || {}

      if (!prompt || typeof prompt !== 'string' || prompt.trim().length < 10) {
        return reply.status(400).send({ error: { code: 'INVALID_PROMPT', message: 'Prompt must be at least 10 characters.' } })
      }

      const type = skillType || 'nl'

      const systemPrompt = `You are a skill designer for the Kuvalam AI agent platform. Given a user's description of what they want a skill to do, generate a JSON object with the appropriate fields based on the skill type.

Skill type requested: ${type}${type === 'code' ? ` (language: ${language || 'javascript'})` : ''}

For ALL types, include:
- "name": snake_case skill name (max 40 chars, e.g. "send_email", "lookup_order")
- "description": One-line summary of what the skill does and when to use it (max 100 chars)

For "nl" (Natural Language) skills, also include:
- "instruction": Detailed plain-English steps the agent should follow. Be specific about what tools to use, data flow, and output format. (200-600 chars)

For "api" skills, also include:
- "url": The API endpoint URL. Use {{input.param}} for dynamic args and {{config.secret}} for secrets.
- "method": HTTP method (GET, POST, PUT, DELETE)
- "headers": JSON object of headers (as a stringified JSON object)
- "bodyTemplate": For POST/PUT/PATCH, JSON body template with {{input.param}} placeholders (as stringified JSON). Omit for GET/DELETE.

For "code" skills, also include:
- "code": The full code.${language === 'python' ? ' Python code with a def run(input): function that returns a dict. Use only stdlib unless essential.' : ' JavaScript code using the input object. fetch() is available globally. Return a value or object.'}

Rules:
- Return ONLY valid JSON — no markdown, no backticks, no explanation.
- Make practical, useful skills that an AI agent would actually call.
- For NL skills, mention concrete tool names (from the list: list_tables, describe_table, query, run_query, read_file, write_file, list_files, search_files, browse_url, browser_use, web_search, calculator, clock, email_send, slack_send_message, publish_dashboard_report, http_request, http_download, file_search, docker_run, ssh_exec, delegate_task, a2a_call).
- For API skills, use realistic endpoint patterns.
- For code skills, write clean, error-handled code that validates input.`

      const messages = [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Create a ${type === 'nl' ? 'natural language' : type === 'api' ? 'API/webhook' : 'code'} skill that: ${prompt.trim()}` },
      ]

      // Get tenant LLM config
      const { query: dbQuery } = await import('../db/pool.js')
      const { rows } = await dbQuery(
        'SELECT llm_config FROM tenants WHERE id = $1',
        [tenantId]
      )
      const llmConfig = rows?.[0]?.llm_config || {}

      const { complete } = await import('../services/llm.service.js')

      const result = await complete({
        tenantId,
        agentId: 'skill-generator',
        messages,
        llmConfig,
        useSystemLlm: true,
        temperature: 0.2,
        goal: `Generate skill from prompt: ${prompt.trim().slice(0, 80)}`,
      })

      // Parse the LLM response as JSON
      const text = (result.content || '').trim()
      let parsed
      try {
        const clean = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '')
        parsed = JSON.parse(clean)
      } catch {
        return reply.status(422).send({
          error: { code: 'PARSE_ERROR', message: 'Failed to parse generated skill. Please try rephrasing your prompt.', raw: text.slice(0, 500) }
        })
      }

      return {
        data: {
          name: parsed.name || 'custom_skill',
          description: parsed.description || `AI-generated skill: ${prompt.trim().slice(0, 60)}…`,
          type,
          instruction: parsed.instruction || undefined,
          code: parsed.code || undefined,
          language: language || parsed.language || undefined,
          url: parsed.url || undefined,
          method: parsed.method || undefined,
          headers: parsed.headers || undefined,
          bodyTemplate: parsed.bodyTemplate || undefined,
        }
      }
    } catch (err) {
      if (err.message === 'LLM_RATE_LIMITED') {
        return reply.status(429).send({ error: { code: 'RATE_LIMITED', message: 'LLM rate limit reached. Please try again in a moment.' } })
      }
      if (err.message === 'LLM_AUTH_ERROR') {
        return reply.status(400).send({ error: { code: 'LLM_NOT_CONFIGURED', message: 'No LLM configured for this tenant. Set up an API key in Settings.' } })
      }
      return errorResponse(reply, err)
    }
  })

  // GET /tenants/:tenantId/agents
  fastify.get('/tenants/:tenantId/agents', auth, async (req, reply) => {
    try {
      const result = await agentService.listAgents(req.params.tenantId, req.query)
      return reply.send({ success: true, data: result, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // GET /tenants/:tenantId/agents/:agentId
  fastify.get('/tenants/:tenantId/agents/:agentId', auth, async (req, reply) => {
    try {
      const agent = await agentService.getAgent(req.params.tenantId, req.params.agentId)
      return reply.send({ success: true, data: agent, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // DELETE /tenants/:tenantId/agents/:agentId
  fastify.delete('/tenants/:tenantId/agents/:agentId', auth, async (req, reply) => {
    try {
      await agentService.deleteAgent(req.params.tenantId, req.params.agentId, req.user.sub)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // PATCH /tenants/:tenantId/agents/:agentId
  fastify.patch('/tenants/:tenantId/agents/:agentId', auth, async (req, reply) => {
    try {
      const agent = await agentService.updateAgent(req.params.tenantId, req.params.agentId, req.body, req.user.sub)
      return reply.send({ success: true, data: agent, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/activate
  fastify.post('/tenants/:tenantId/agents/:agentId/activate', auth, async (req, reply) => {
    try {
      const agent = await agentService.activateAgent(req.params.tenantId, req.params.agentId, req.user.sub)
      return reply.send({ success: true, data: agent, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/duplicate
  fastify.post('/tenants/:tenantId/agents/:agentId/duplicate', auth, async (req, reply) => {
    try {
      const src = await agentService.getAgent(req.params.tenantId, req.params.agentId)
      if (!src) throw new AppError('NOT_FOUND', 'Agent not found', 404)
      const clone = await agentService.createAgent({
        tenantId: req.params.tenantId,
        userId: req.user.sub,
        data: {
          // NOTE: createAgent expects camelCase field names — do not pass snake_case here,
          // otherwise the source agent's LLM choice, prompt and autonomy level are silently lost.
          name: `${src.name} (copy)`,
          description: src.description,
          archetype: src.archetype,
          llmProvider: src.llm_provider,
          llmModel: src.llm_model,
          systemPrompt: src.system_prompt,
          autonomyLevel: src.autonomy_level,
          confidenceThreshold: src.confidence_threshold,
          maxActionsPerRun: src.max_actions_per_run,
        },
      })
      return reply.status(201).send({ success: true, data: clone, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/skills
  fastify.post('/tenants/:tenantId/agents/:agentId/skills', auth, async (req, reply) => {
    try {
      const skill = await agentService.addSkill(req.params.tenantId, req.params.agentId, req.body, req.user.sub)
      return reply.status(201).send({ success: true, data: skill, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/rules
  fastify.post('/tenants/:tenantId/agents/:agentId/rules', auth, async (req, reply) => {
    try {
      const rule = await agentService.addRule(req.params.tenantId, req.params.agentId, req.body, req.user.sub)
      return reply.status(201).send({ success: true, data: rule, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/test-skill
  fastify.post('/tenants/:tenantId/agents/:agentId/test-skill', {
    schema: { params: agentIdParam },
    preHandler: [fastify.authenticate, requirePermission('skill:test')]
  }, async (req, reply) => {
    try {
      const { code, input, env } = req.body
      const result = await executeCustomSkill(code, input || {}, env || {})
      return reply.send({ success: true, data: result, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // GET /tenants/:tenantId/agents/:agentId/preview-prompt
  // Returns the full system prompt that would be used when this agent executes a task.
  // Optional query param ?goal=... injects the task goal so the preview matches runtime exactly.
  fastify.get('/tenants/:tenantId/agents/:agentId/preview-prompt', {
    schema: { params: agentIdParam },
    preHandler: [fastify.authenticate]
  }, async (req, reply) => {
    try {
      const { agentId, tenantId } = req.params
      const goal = String(req.query?.goal || '').trim()
      const agent = await agentService.getAgent(tenantId, agentId)
      if (!agent) throw new AppError('AGENT_NOT_FOUND', 'Agent not found', 404)

      // ── Enrich agent with runtime context (same as task.service.js) ──
      // The raw DB row doesn't have _dbConnectionString, _dataStrategy,
      // _hasKnowledgeContext etc. — these are computed at runtime. We
      // replicate the essential enrichment so the preview matches reality.

      // 1. Load skills from agent_skills (explicit skill assignments)
      const { query } = await import('../db/pool.js')
      const { rows: agentSkills } = await query(
        'SELECT * FROM agent_skills WHERE agent_id = $1 AND is_enabled = true',
        [agent.id]
      ).catch(() => ({ rows: [] }))

      // 1b. Load builtin tool scopes from agent_tool_scopes — these are the
      // tools the agent actually has allowed at runtime (write_artifact,
      // browser_use, http_request, etc.). Merge them into the skills array
      // so buildRuntimeContext and tool stripping see the real tool set.
      const { rows: toolScopes } = await query(
        `SELECT builtin_name AS name, builtin_name AS description
         FROM agent_tool_scopes
         WHERE agent_id = $1 AND scope_type = 'builtin' AND access_level = 'allowed'`,
        [agent.id]
      ).catch(() => ({ rows: [] }))

      // Merge: agent_skills take priority, tool scopes fill gaps
      const existingSkillNames = new Set(agentSkills.map(s => s.name.toLowerCase()))
      const mergedSkills = [...agentSkills]
      for (const ts of toolScopes) {
        if (!existingSkillNames.has(ts.name.toLowerCase())) {
          mergedSkills.push(ts)
        }
      }
      const skills = mergedSkills

      // 2. Data strategy
      agent._dataStrategy = agent.data_strategy || 'none'

      // 3. KB / knowledge graph detection
      const kbCount = Array.isArray(agent.knowledge_base_ids) ? agent.knowledge_base_ids.length : 0
      const graphCount = Array.isArray(agent.knowledge_graph_ids) ? agent.knowledge_graph_ids.length : 0
      if (kbCount > 0 || graphCount > 0) {
        agent._hasKnowledgeContext = true
      }

      // 4. DB connection resolution (replicating task.service.js logic)
      let dbResolved = false
      // 4a. Trained custom model lookup
      try {
        const { rows: dbRows } = await query(
          `SELECT cmd.db_label, cmd.db_connection_string, cmd.db_type,
                  cm.model_name
           FROM custom_model_databases cmd
           JOIN custom_models cm ON cm.id = cmd.model_id
           WHERE cm.tenant_id = $1
             AND cm.data_source IN ('database', 'nosql')
             AND cm.status = 'COMPLETED'
             AND cmd.db_connection_string IS NOT NULL
             AND cmd.db_connection_string != ''
             AND (cm.model_name = $2
                  OR cm.model_name = split_part($2, ':', 1)
                  OR cm.model_name LIKE $2 || '_%')
           ORDER BY cmd.sort_order`,
          [agent.tenant_id, agent.llm_model]
        )
        if (dbRows.length > 0) {
          agent._dbConnectionString = dbRows[0].db_connection_string
          agent._dbType = dbRows[0].db_type || 'postgresql'
          agent._isTrainedModel = true
          if (dbRows.length > 1) {
            agent._dbConnectionMap = new Map()
            for (const row of dbRows) {
              agent._dbConnectionMap.set(row.db_label, {
                connectionString: row.db_connection_string,
                dbType: row.db_type,
              })
            }
          }
          dbResolved = true
        }
      } catch { /* fall through */ }

      // 4b. Connector-scope fallback
      if (!dbResolved) {
        try {
          const { decryptCredentials } = await import('../services/crypto.service.js')
          const { rows: connRows } = await query(
            `SELECT tc.config, tc.id
             FROM agent_tool_scopes ats
             JOIN tool_connections tc ON ats.connector_id = tc.id
             WHERE ats.agent_id = $1 AND ats.scope_type = 'connector'
               AND tc.tool_id = ANY(ARRAY['database','postgres','mysql','snowflake','redshift','bigquery','mssql','sqlite','mongodb'])
               AND tc.status = 'ACTIVE'
             ORDER BY tc.created_at ASC LIMIT 1`,
            [agent.id]
          )
          const cfg = connRows[0]?.config
          if (cfg) {
            const decrypted = decryptCredentials(cfg)
            const host = decrypted.host || 'localhost'
            const port = decrypted.port || '5432'
            const user = decrypted.user || decrypted.username || 'postgres'
            const database = decrypted.database || decrypted.db || 'postgres'
            const password = decrypted.password || ''
            const ssl = decrypted.ssl === 'require' || decrypted.ssl === 'true' ? '?sslmode=require' : ''
            agent._dbConnectionString = `postgresql://${user}:${encodeURIComponent(password)}@${host}:${port}/${database}${ssl}`
            agent._dbType = decrypted.dbType || decrypted.db_type || 'postgresql'
            agent._activeDbName = database
            dbResolved = true
          }
        } catch { /* fall through */ }
      }

      // ── Load scoped builtin tool names so the prompt builder knows which
      // tools (publish_dashboard_report, browser_use, http_request, etc.)
      // the agent actually has. This drives tool detection, goal-gating,
      // and delivery-channel display in the generated prompt.
      let builtinToolNames = []
      try {
        const { rows: scopeRows } = await query(
          `SELECT builtin_name FROM agent_tool_scopes
           WHERE agent_id = $1 AND scope_type = 'builtin'
             AND access_level IN ('allowed', 'requires_approval')`,
          [agent.id]
        )
        builtinToolNames = scopeRows.map(r => r.builtin_name).filter(Boolean)
      } catch { /* non-critical — prompt will just lack builtin tool awareness */ }

      // ── Build prompt with real runtime context ──
      const { buildSystemPrompt } = await import('../services/task-reports.js')
      let fullPrompt = await buildSystemPrompt(agent, skills, goal, builtinToolNames)

      // Defensive: strip duplicated section headings that may have accumulated
      // from earlier corrupted Teach Agent runs.  Only the first occurrence of
      // each heading family is kept, subsequent duplicates are removed.
      fullPrompt = fullPrompt
        .replace(/(\n##\s+AGENT[- ]SPECIFIC\s+INSTRUCTIONS\s*\n(?:(?!\n##\s).*\n)*)(\n##\s+AGENT[- ]SPECIFIC\s+INSTRUCTIONS\s*(?:\n|$))+/g, '$1')
        .replace(/(\n##\s+Guardrails?\s*(?:\([^)]*\))?\s*\n(?:(?!\n##\s).*\n)*)(\n##\s+Guardrails?\s*(?:\([^)]*\))?\s*(?:\n|$))+/g, '$1')
        .replace(/\n{3,}/g, '\n\n')

      const estimatedTokens = Math.ceil(fullPrompt.length / 4)
      const sectionCount = (fullPrompt.match(/^## /mg) || []).length || 1
      const tokensPerChunk = Math.ceil(estimatedTokens / sectionCount)

      return reply.send({
        success: true,
        data: {
          agentId,
          agentName: agent.name,
          archetype: agent.archetype,
          systemPrompt: fullPrompt,
          hasCustomInstructions: !!String(agent.system_prompt || '').trim(),
          charCount: fullPrompt.length,
          estimatedTokens,
          chunkStats: { sectionCount, tokensPerChunk }
        },
        meta: ts()
      })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/compress-prompt
  // Summarise the full system prompt into a compact version.
  // Tries LLM compression first; falls back to rule-based compression if the LLM
  // is unavailable, rate-limited, or not configured.
  fastify.post('/tenants/:tenantId/agents/:agentId/compress-prompt', {
    schema: { params: agentIdParam },
    preHandler: [fastify.authenticate]
  }, async (req, reply) => {
    try {
      const { tenantId, agentId } = req.params
      const save = !!req.body?.save
      const mode = req.body?.mode || 'ai'  // 'ai' | 'local'
      const goal = String(req.body?.goal || '').trim()

      const agent = await agentService.getAgent(tenantId, agentId)
      if (!agent) throw new AppError('AGENT_NOT_FOUND', 'Agent not found', 404)

      const { buildSystemPrompt } = await import('../services/task-reports.js')

      const fullPrompt = await buildSystemPrompt(agent, [], goal)
      const fullTokens = Math.ceil(fullPrompt.length / 4)

      let compressedPrompt = ''
      let method = 'llm'

      // Local mode: rule-based only — no LLM call at all
      if (mode === 'local') {
        method = 'local'
        compressedPrompt = ruleBasedCompress(fullPrompt)
        const compressedTokens = Math.ceil(compressedPrompt.length / 4)
        const savedPct = Math.round((1 - compressedTokens / fullTokens) * 100)
        if (save) {
          await agentService.updateAgent(tenantId, agentId, { local_refine_prompt: true, compress_system_prompt: false }, req.user.sub)
        }
        return reply.send({ success: true, data: { fullPrompt, compressedPrompt, fullTokens, compressedTokens, savedPct, saved: save, method }, meta: ts() })
      }

      const { complete } = await import('../services/llm.service.js')
      const { stripThinkBlocks } = await import('../services/task-json-repair.js')

      // 1. Try LLM compression
      // CRITICAL: must pass the agent's own llm_config + provider + model so the
      // call routes to the agent's configured LLM. Omitting these made every AI
      // compression resolve to a default config that failed (rate-limited /
      // unconfigured) and silently fell back to rule-based — identical to local.
      try {
        const result = await complete({
          tenantId,
          agentId,
          messages: [
            {
              role: 'system',
              content: 'You are a system prompt compressor. Rewrite the provided AI agent system prompt as a dense, compact version that is SHORTER than the original. CRITICAL RULES: (1) NEVER remove or change any number, quantity, measurement, count, or specific value — preserve all numeric values and units exactly as written. (2) NEVER remove proper nouns, project names, or named entities. (3) Preserve ALL rules, constraints, capabilities, and behavioral directives. (4) Remove only verbose filler words and redundant explanations. (5) Do NOT add any commentary, thinking, <think> tags, headings, or preamble — output ONLY the compressed prompt text itself, no markdown fences.'
            },
            { role: 'user', content: fullPrompt }
          ],
          llmConfig: agent.llm_config,
          provider: agent.llm_provider,
          model: agent.llm_model,
          // 4096, NOT 2000: reasoning models (qwen3 on Groq/Ollama) spend most
          // tokens inside a <think> block before emitting the compressed prompt.
          // 2000 truncated mid-thought → empty/partial output → rule fallback.
          maxTokens: 4096,
          temperature: 0.1
        })
        // qwen3/reasoning models prepend a verbose <think> block — strip it so
        // the token count reflects the real compressed prompt, not the reasoning.
        let llmCompressed = stripThinkBlocks(String(result?.content ?? result ?? ''))
        // Only accept the LLM result if it's genuinely a smaller prompt. If the
        // model expanded the prompt or returned garbage, prefer rule-based.
        if (llmCompressed && llmCompressed.length < fullPrompt.length && llmCompressed.length > 50) {
          compressedPrompt = llmCompressed
        } else {
          method = 'rules'
          compressedPrompt = ruleBasedCompress(fullPrompt)
        }
      } catch (llmErr) {
        // 2. Fallback: rule-based compression (works without any LLM)
        method = 'rules'
        compressedPrompt = ruleBasedCompress(fullPrompt)
      }

      if (!compressedPrompt) compressedPrompt = ruleBasedCompress(fullPrompt)

      const compressedTokens = Math.ceil(compressedPrompt.length / 4)
      const savedPct = Math.round((1 - compressedTokens / fullTokens) * 100)

      if (save) {
        await agentService.updateAgent(tenantId, agentId, { compress_system_prompt: true }, req.user.sub)
      }

      return reply.send({
        success: true,
        data: {
          fullPrompt, compressedPrompt, fullTokens, compressedTokens, savedPct, saved: save, method,
          // Chunked overhead analysis — same content as full, but adds priming messages
          // Overhead: 1 priming system msg (~30t) + per-section: label (~8t) + ack (~18t) = 26t/section
          chunked: (() => {
            const sectionCount = (fullPrompt.match(/^## /mg) || []).length || 1
            const overheadTokens = 30 + sectionCount * 26
            return { sectionCount, overheadTokens, totalTokens: fullTokens + overheadTokens }
          })()
        },
        meta: ts()
      })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/refine-prompt — use the agent's LLM to
  // refine its system instructions (guardrails) from a user scenario. Returns a
  // suggested prompt + summary; does NOT auto-save (client applies via PATCH).
  fastify.post('/tenants/:tenantId/agents/:agentId/refine-prompt', {
    schema: { params: agentIdParam },
    preHandler: [fastify.authenticate]
  }, async (req, reply) => {
    try {
      const { tenantId, agentId } = req.params
      const scenario = String(req.body?.scenario || '').trim()
      if (!scenario) throw new AppError('MISSING_SCENARIO', 'A scenario or rule is required to refine the prompt', 400)
      const systemPrompt = req.body?.systemPrompt
      const goal = req.body?.goal
      const result = await agentService.refineAgentPrompt(tenantId, agentId, scenario, systemPrompt, goal)
      return reply.send({ success: true, data: result, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // GET /tenants/:tenantId/agents/:agentId/system-prompt/history — list saved
  // prompt versions (newest first) so the UI can preview/restore one.
  fastify.get('/tenants/:tenantId/agents/:agentId/system-prompt/history', {
    schema: { params: agentIdParam },
    preHandler: [fastify.authenticate]
  }, async (req, reply) => {
    try {
      const data = await agentService.getPromptHistory(req.params.tenantId, req.params.agentId)
      return reply.send({ success: true, data, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/system-prompt/undo — restore the
  // most recent prompt version (or a specific one via body.index).
  fastify.post('/tenants/:tenantId/agents/:agentId/system-prompt/undo', {
    schema: { params: agentIdParam },
    preHandler: [fastify.authenticate]
  }, async (req, reply) => {
    try {
      const index = req.body?.index === undefined ? null : req.body.index
      const data = await agentService.undoPromptChange(req.params.tenantId, req.params.agentId, req.user.sub, index)
      return reply.send({ success: true, data, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/knowledge-bases/:kbId
  fastify.post('/tenants/:tenantId/agents/:agentId/knowledge-bases/:kbId', auth, async (req, reply) => {
    try {
      await agentService.linkKnowledgeBase(req.params.tenantId, req.params.agentId, req.params.kbId, req.user.sub)
      return reply.send({ success: true, data: { linked: true }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // DELETE /tenants/:tenantId/agents/:agentId/knowledge-bases/:kbId
  fastify.delete('/tenants/:tenantId/agents/:agentId/knowledge-bases/:kbId', auth, async (req, reply) => {
    try {
      await agentService.unlinkKnowledgeBase(req.params.tenantId, req.params.agentId, req.params.kbId, req.user.sub)
      return reply.send({ success: true, data: { unlinked: true }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/tasks — dispatch a task
  fastify.post('/tenants/:tenantId/agents/:agentId/tasks', {
    schema: { params: agentIdParam, ...dispatchTaskSchema },
    preHandler: [fastify.authenticate, requirePermission('agent:execute')]
  }, async (req, reply) => {
    try {
      await checkTenantTaskRateLimit(req.params.tenantId)
      const result = await taskService.dispatchTask({
        tenantId: req.params.tenantId,
        agentId: req.params.agentId,
        ...req.body,
        userId: req.user.sub
      })
      return reply.status(202).send({ success: true, data: result, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // GET /tenants/:tenantId/agents/:agentId/tasks
  fastify.get('/tenants/:tenantId/agents/:agentId/tasks', auth, async (req, reply) => {
    try {
      const tasks = await taskService.listTasks(req.params.tenantId, req.params.agentId, req.query)
      return reply.send({ success: true, data: { tasks }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // GET /tenants/:tenantId/agents/:agentId/tasks/:taskId
  fastify.get('/tenants/:tenantId/agents/:agentId/tasks/:taskId', auth, async (req, reply) => {
    try {
      const task = await taskService.getTask(req.params.tenantId, req.params.taskId)
      return reply.send({ success: true, data: task, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/tasks/:taskId/cancel
  fastify.post('/tenants/:tenantId/agents/:agentId/tasks/:taskId/cancel', auth, async (req, reply) => {
    try {
      await taskService.cancelTask(req.params.tenantId, req.params.agentId, req.params.taskId, req.user.sub)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // POST /tenants/:tenantId/agents/:agentId/tasks/:taskId/retry
  // Body: { mode?: 'checkpoint' | 'fresh' }  — defaults to 'checkpoint' if a snapshot exists
  fastify.post('/tenants/:tenantId/agents/:agentId/tasks/:taskId/retry', {
    preHandler: [fastify.authenticate, requirePermission('agent:execute')]
  }, async (req, reply) => {
    try {
      const mode = req.body?.mode === 'fresh' ? 'fresh' : 'checkpoint'
      const task = await taskService.retryTask(req.params.tenantId, req.params.agentId, req.params.taskId, req.user.sub, { mode })
      return reply.code(202).send({ success: true, task, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // DELETE /tenants/:tenantId/agents/:agentId/skills/:skillId
  fastify.delete('/tenants/:tenantId/agents/:agentId/skills/:skillId', auth, async (req, reply) => {
    try {
      await agentService.removeSkill(req.params.tenantId, req.params.agentId, req.params.skillId, req.user.sub)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // DELETE /tenants/:tenantId/agents/:agentId/rules/:ruleId
  fastify.delete('/tenants/:tenantId/agents/:agentId/rules/:ruleId', auth, async (req, reply) => {
    try {
      await agentService.removeRule(req.params.tenantId, req.params.agentId, req.params.ruleId, req.user.sub)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // DELETE /tenants/:tenantId/agents/:agentId/tasks/:taskId
  fastify.delete('/tenants/:tenantId/agents/:agentId/tasks/:taskId', auth, async (req, reply) => {
    try {
      await agentService.deleteTask(req.params.tenantId, req.params.agentId, req.params.taskId, req.user.sub)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // ═════════════════════════════════════════════════════════════════════════════
  // Agent Memory — long-term entity memory + episodic (past-experience) memory
  // ═════════════════════════════════════════════════════════════════════════════

  // GET  /tenants/:tenantId/agents/:agentId/memory          — list all memory
  // DELETE /tenants/:tenantId/agents/:agentId/memory        — clear ALL memory
  // DELETE /tenants/:tenantId/agents/:agentId/memory/:memoryId   — delete one entity entry
  // DELETE /tenants/:tenantId/agents/:agentId/memory/episodic/:memoryId — delete one episodic entry

  fastify.get('/tenants/:tenantId/agents/:agentId/memory', auth, async (req, reply) => {
    try {
      const { tenantId, agentId } = req.params
      const entityMemory = await memoryService.listMemory(agentId, tenantId)
      const episodicMemory = await taskKnowledgeService.listEpisodicMemory(agentId, tenantId)
      return reply.send({ success: true, data: { entityMemory, episodicMemory }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  fastify.delete('/tenants/:tenantId/agents/:agentId/memory', auth, async (req, reply) => {
    try {
      const { tenantId, agentId } = req.params
      await memoryService.clearMemory(agentId, tenantId)
      await taskKnowledgeService.clearEpisodicMemory(agentId, tenantId)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  fastify.delete('/tenants/:tenantId/agents/:agentId/memory/episodic/:memoryId', auth, async (req, reply) => {
    try {
      const { tenantId, agentId, memoryId } = req.params
      await taskKnowledgeService.deleteEpisodicMemoryEntry(agentId, tenantId, memoryId)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  fastify.delete('/tenants/:tenantId/agents/:agentId/memory/:memoryId', auth, async (req, reply) => {
    try {
      const { tenantId, agentId, memoryId } = req.params
      await memoryService.deleteMemoryEntry(agentId, tenantId, memoryId)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // ═════════════════════════════════════════════════════════════════════════════
  // Agent Tool Scopes — define which connectors/MCPs/built-ins an agent can use
  // ═════════════════════════════════════════════════════════════════════════════

  // GET  /tenants/:tenantId/agents/:agentId/scopes              — list scopes
  // POST /tenants/:tenantId/agents/:agentId/scopes              — add scope
  // PATCH /tenants/:tenantId/agents/:agentId/scopes/:scopeId    — update scope level
  // DELETE /tenants/:tenantId/agents/:agentId/scopes/:scopeId   — remove scope
  // PUT  /tenants/:tenantId/agents/:agentId/scopes              — bulk replace all scopes
  // GET  /tenants/:tenantId/agents/:agentId/scopes/presets      — archetype preset suggestions

  fastify.get('/tenants/:tenantId/agents/:agentId/scopes', auth, async (req, reply) => {
    try {
      const scopes = await scopeService.listScopes(req.params.tenantId, req.params.agentId)
      return reply.send({ success: true, data: { scopes }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  fastify.post('/tenants/:tenantId/agents/:agentId/scopes', {
    ...auth,
    preHandler: [fastify.authenticate, requirePermission('agent:scopes')]
  }, async (req, reply) => {
    try {
      const scope = await scopeService.addScope(req.params.tenantId, req.params.agentId, req.body)
      return reply.status(201).send({ success: true, data: scope, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  fastify.patch('/tenants/:tenantId/agents/:agentId/scopes/:scopeId', {
    ...auth,
    preHandler: [fastify.authenticate, requirePermission('agent:scopes')]
  }, async (req, reply) => {
    try {
      const scope = await scopeService.updateScope(req.params.tenantId, req.params.agentId, req.params.scopeId, req.body)
      return reply.send({ success: true, data: scope, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  fastify.delete('/tenants/:tenantId/agents/:agentId/scopes/:scopeId', {
    ...auth,
    preHandler: [fastify.authenticate, requirePermission('agent:scopes')]
  }, async (req, reply) => {
    try {
      await scopeService.removeScope(req.params.tenantId, req.params.agentId, req.params.scopeId)
      return reply.send({ success: true, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // Bulk replace all scopes (send array of scope objects)
  fastify.put('/tenants/:tenantId/agents/:agentId/scopes', {
    ...auth,
    preHandler: [fastify.authenticate, requirePermission('agent:scopes')]
  }, async (req, reply) => {
    try {
      const scopes = await scopeService.setScopes(req.params.tenantId, req.params.agentId, req.body.scopes || [])
      return reply.send({ success: true, data: { scopes }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })

  // Get archetype-based scope presets — returns ALL archetypes so the UI can
  // let the user pick presets for any archetype regardless of the agent's own.
  fastify.get('/tenants/:tenantId/agents/:agentId/scopes/presets', auth, async (req, reply) => {
    try {
      const allArchetypes = ['customer-support', 'data-analyst', 'developer', 'browser-automation', 'analyst']
      const presets = {}
      for (const a of allArchetypes) {
        const p = scopeService.getArchetypeScopePresets(a)
        if (p) presets[a] = p
      }
      return reply.send({ success: true, data: { presets }, meta: ts() })
    } catch (err) { return errorResponse(reply, err) }
  })
}

const ts = () => ({ timestamp: new Date().toISOString() })
